---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiber-gateway
  labels:
    app: fiber-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: fiber-gateway
      labels:
        app: fiber-gateway
    spec:
      containers:
        - name: fiber-gateway
          image: tammo0987/fiber-gateway:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              hostPort: 80
              protocol: TCP
          env:
            - name: SECRET_JWT
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
      restartPolicy: Always
  selector:
    matchLabels:
      app: fiber-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: fiber-gateway
spec:
  selector:
    app: fiber-gateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  template:
    metadata:
      name: cassandra
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra
          ports:
            - containerPort: 9042
              hostPort: 9042
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
data:
  secret: Test
---