---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: fiber
  labels:
    app: cassandra
spec:
  replicas: 1
  template:
    metadata:
      name: cassandra
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra
          ports:
            - containerPort: 9042
              hostPort: 9042
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: fiber
spec:
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
  type: ClusterIP
---