---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
  namespace: fiber
type: Opaque
data:
  secret: Test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fiber-gateway
  namespace: fiber
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-pods
  namespace: fiber
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-pods_fiber-gateway
  namespace: fiber
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-pods
subjects:
  - kind: ServiceAccount
    name: fiber-gateway
    namespace: fiber
---